// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBACBwxW5QFLgH69x20uXxPRLhkceNeaWA',
    appId: '1:787757052851:web:b4ee9354fb4a734a2211c6',
    messagingSenderId: '787757052851',
    projectId: 'awa-builder',
    authDomain: 'awa-builder.firebaseapp.com',
    storageBucket: 'awa-builder.appspot.com',
    measurementId: 'G-HB0658N5DW',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3RnAUc4bAKM6X9m9G-_gMYI8VrhuJm20',
    appId: '1:787757052851:ios:49033f62005ee42c2211c6',
    messagingSenderId: '787757052851',
    projectId: 'awa-builder',
    storageBucket: 'awa-builder.appspot.com',
    iosClientId:
        '787757052851-qd30soo7tiqlu17r0ddcvpm5kba7sg8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.automationWrapperBuilder',
  );
}
